name = "line-hono-test"
compatibility_date = "2023-12-01"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

compatibility_flags = [ "nodejs_compat" ]
[triggers]
crons = [
  "0 0 * * *",      # 毎日0:00に実行
  "20 13 * * 1-5",  # 平日13:20に実行
  "0 7 * * 1"       # 毎週月曜7:00に実行
]
[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "db_20_test"
database_id = "e5de49ec-20df-4be2-af32-732d17f66530"